### Makefile for ruby  ###
MAKE = nmake
srcdir = ./..
prefix = /usr
EXTSTATIC = 
!ifndef TARGET_OS
TARGET_OS = mswin32
!endif
OS = $(TARGET_OS)
RT = msvcrt





























































MAJOR = 1
MINOR = 9
TEENY = 0
MSC_VER = 1200
PROCESSOR_ARCHITECTURE = x86
PROCESSOR_LEVEL = 6

BUILTIN_ENCOBJS = ascii.obj euc_jp.obj sjis.obj unicode.obj utf8.obj 




configure_args = 


# RUBY_INSTALL_NAME = ruby
# RUBY_SO_NAME = $(RT)-$(RUBY_INSTALL_NAME)$(MAJOR)$(MINOR)
# CFLAGS = -nologo -MD $(DEBUGFLAGS) $(OPTFLAGS) $(PROCESSOR_FLAG)
# CPPFLAGS = -I. -I$(srcdir) -I$(srcdir)/missing -DLIBRUBY_SO=\"$(LIBRUBY_SO)\"
# STACK = 0x2000000
# LDFLAGS = $(CFLAGS) -Fm
# XLDFLAGS = 
# RFLAGS = -r
# EXTLIBS =

!include $(srcdir)/win32/Makefile.sub
